version: "3"
services:
  frontend:
    container_name: DVDash_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: natalie/dvdash
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  backend:
    container_name: DVDash_api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: natalie/dvdash
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
